% Based on a code generated by Claude (Anthlopic)

clear;
timestamp = datetime('now', 'Format', 'yyyyMMdd_HHmmss');
logfile = sprintf('log%s.txt', char(timestamp));
diary(logfile);
diary on

fprintf('実行開始: %s\n', char(timestamp));
fprintf('ログファイル: %s\n\n', logfile);
content = fileread('input_data.m');
disp(content);

scripts = {'approximate_solution.m', 'FN_Int.m', 'unimodality.m'};

for i = 1:length(scripts)
    fprintf('[%d/%d] 実行中: %s\n', i, length(scripts), scripts{i});
    run(scripts{i});
    fprintf('→ 完了\n');
end

timestamp = datetime('now', 'Format', 'yyyyMMdd_HHmmss');
fprintf('\n実行終了: %s\n', char(timestamp));
diary off